### ISSUE TITLE
Exception on reload page

### ISSUE THREAD

**Issue by Fredy7777** [TrevorMare/STGTour#9]
**Bug Description**
There is a way to provoke a ObjectDisposedException.

**Repro steps**
- Start the Guided Tour Demo
- Click "Start form Tour"
- Press F5
- Click "Start form Tour"
- ObjectDisposedException will be thrown

azor.server.js:21 [2023-04-25T12:46:14.195Z] Error: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'JSObjectReference'.
   at Microsoft.JSInterop.Implementation.JSObjectReference.ThrowIfDisposed()
   at Microsoft.JSInterop.Implementation.JSObjectReference.InvokeAsync[TValue](String identifier, Object[] args)
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeAsync[TValue](IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at GTour.Interops.JsInteropCommon.RemoveClassFromElement(String elementSelector, String className) in ...

**Comment by Jinjinov** [comment]
@Fredy7777 you can use `<GuidedTour HighlightEnabled="false">` because this bug only happens if `HighlightEnabled="true"`
